require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuyHousesController do

  # This should return the minimal set of attributes required to create a valid
  # BuyHouse. As you add validations to BuyHouse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuyHousesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all buy_houses as @buy_houses" do
      buy_house = BuyHouse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:buy_houses).should eq([buy_house])
    end
  end

  describe "GET show" do
    it "assigns the requested buy_house as @buy_house" do
      buy_house = BuyHouse.create! valid_attributes
      get :show, {:id => buy_house.to_param}, valid_session
      assigns(:buy_house).should eq(buy_house)
    end
  end

  describe "GET new" do
    it "assigns a new buy_house as @buy_house" do
      get :new, {}, valid_session
      assigns(:buy_house).should be_a_new(BuyHouse)
    end
  end

  describe "GET edit" do
    it "assigns the requested buy_house as @buy_house" do
      buy_house = BuyHouse.create! valid_attributes
      get :edit, {:id => buy_house.to_param}, valid_session
      assigns(:buy_house).should eq(buy_house)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BuyHouse" do
        expect {
          post :create, {:buy_house => valid_attributes}, valid_session
        }.to change(BuyHouse, :count).by(1)
      end

      it "assigns a newly created buy_house as @buy_house" do
        post :create, {:buy_house => valid_attributes}, valid_session
        assigns(:buy_house).should be_a(BuyHouse)
        assigns(:buy_house).should be_persisted
      end

      it "redirects to the created buy_house" do
        post :create, {:buy_house => valid_attributes}, valid_session
        response.should redirect_to(BuyHouse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved buy_house as @buy_house" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuyHouse.any_instance.stub(:save).and_return(false)
        post :create, {:buy_house => { "user_id" => "invalid value" }}, valid_session
        assigns(:buy_house).should be_a_new(BuyHouse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuyHouse.any_instance.stub(:save).and_return(false)
        post :create, {:buy_house => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested buy_house" do
        buy_house = BuyHouse.create! valid_attributes
        # Assuming there are no other buy_houses in the database, this
        # specifies that the BuyHouse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BuyHouse.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => buy_house.to_param, :buy_house => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested buy_house as @buy_house" do
        buy_house = BuyHouse.create! valid_attributes
        put :update, {:id => buy_house.to_param, :buy_house => valid_attributes}, valid_session
        assigns(:buy_house).should eq(buy_house)
      end

      it "redirects to the buy_house" do
        buy_house = BuyHouse.create! valid_attributes
        put :update, {:id => buy_house.to_param, :buy_house => valid_attributes}, valid_session
        response.should redirect_to(buy_house)
      end
    end

    describe "with invalid params" do
      it "assigns the buy_house as @buy_house" do
        buy_house = BuyHouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuyHouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => buy_house.to_param, :buy_house => { "user_id" => "invalid value" }}, valid_session
        assigns(:buy_house).should eq(buy_house)
      end

      it "re-renders the 'edit' template" do
        buy_house = BuyHouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuyHouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => buy_house.to_param, :buy_house => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested buy_house" do
      buy_house = BuyHouse.create! valid_attributes
      expect {
        delete :destroy, {:id => buy_house.to_param}, valid_session
      }.to change(BuyHouse, :count).by(-1)
    end

    it "redirects to the buy_houses list" do
      buy_house = BuyHouse.create! valid_attributes
      delete :destroy, {:id => buy_house.to_param}, valid_session
      response.should redirect_to(buy_houses_url)
    end
  end

end
