require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JosephMemosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # JosephMemo. As you add validations to JosephMemo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JosephMemosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all joseph_memos as @joseph_memos" do
      joseph_memo = JosephMemo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:joseph_memos)).to eq([joseph_memo])
    end
  end

  describe "GET show" do
    it "assigns the requested joseph_memo as @joseph_memo" do
      joseph_memo = JosephMemo.create! valid_attributes
      get :show, {:id => joseph_memo.to_param}, valid_session
      expect(assigns(:joseph_memo)).to eq(joseph_memo)
    end
  end

  describe "GET new" do
    it "assigns a new joseph_memo as @joseph_memo" do
      get :new, {}, valid_session
      expect(assigns(:joseph_memo)).to be_a_new(JosephMemo)
    end
  end

  describe "GET edit" do
    it "assigns the requested joseph_memo as @joseph_memo" do
      joseph_memo = JosephMemo.create! valid_attributes
      get :edit, {:id => joseph_memo.to_param}, valid_session
      expect(assigns(:joseph_memo)).to eq(joseph_memo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JosephMemo" do
        expect {
          post :create, {:joseph_memo => valid_attributes}, valid_session
        }.to change(JosephMemo, :count).by(1)
      end

      it "assigns a newly created joseph_memo as @joseph_memo" do
        post :create, {:joseph_memo => valid_attributes}, valid_session
        expect(assigns(:joseph_memo)).to be_a(JosephMemo)
        expect(assigns(:joseph_memo)).to be_persisted
      end

      it "redirects to the created joseph_memo" do
        post :create, {:joseph_memo => valid_attributes}, valid_session
        expect(response).to redirect_to(JosephMemo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved joseph_memo as @joseph_memo" do
        post :create, {:joseph_memo => invalid_attributes}, valid_session
        expect(assigns(:joseph_memo)).to be_a_new(JosephMemo)
      end

      it "re-renders the 'new' template" do
        post :create, {:joseph_memo => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested joseph_memo" do
        joseph_memo = JosephMemo.create! valid_attributes
        put :update, {:id => joseph_memo.to_param, :joseph_memo => new_attributes}, valid_session
        joseph_memo.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested joseph_memo as @joseph_memo" do
        joseph_memo = JosephMemo.create! valid_attributes
        put :update, {:id => joseph_memo.to_param, :joseph_memo => valid_attributes}, valid_session
        expect(assigns(:joseph_memo)).to eq(joseph_memo)
      end

      it "redirects to the joseph_memo" do
        joseph_memo = JosephMemo.create! valid_attributes
        put :update, {:id => joseph_memo.to_param, :joseph_memo => valid_attributes}, valid_session
        expect(response).to redirect_to(joseph_memo)
      end
    end

    describe "with invalid params" do
      it "assigns the joseph_memo as @joseph_memo" do
        joseph_memo = JosephMemo.create! valid_attributes
        put :update, {:id => joseph_memo.to_param, :joseph_memo => invalid_attributes}, valid_session
        expect(assigns(:joseph_memo)).to eq(joseph_memo)
      end

      it "re-renders the 'edit' template" do
        joseph_memo = JosephMemo.create! valid_attributes
        put :update, {:id => joseph_memo.to_param, :joseph_memo => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested joseph_memo" do
      joseph_memo = JosephMemo.create! valid_attributes
      expect {
        delete :destroy, {:id => joseph_memo.to_param}, valid_session
      }.to change(JosephMemo, :count).by(-1)
    end

    it "redirects to the joseph_memos list" do
      joseph_memo = JosephMemo.create! valid_attributes
      delete :destroy, {:id => joseph_memo.to_param}, valid_session
      expect(response).to redirect_to(joseph_memos_url)
    end
  end

end
