require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SlotMachinesController do

  # This should return the minimal set of attributes required to create a valid
  # SlotMachine. As you add validations to SlotMachine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SlotMachinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all slot_machines as @slot_machines" do
      slot_machine = SlotMachine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:slot_machines).should eq([slot_machine])
    end
  end

  describe "GET show" do
    it "assigns the requested slot_machine as @slot_machine" do
      slot_machine = SlotMachine.create! valid_attributes
      get :show, {:id => slot_machine.to_param}, valid_session
      assigns(:slot_machine).should eq(slot_machine)
    end
  end

  describe "GET new" do
    it "assigns a new slot_machine as @slot_machine" do
      get :new, {}, valid_session
      assigns(:slot_machine).should be_a_new(SlotMachine)
    end
  end

  describe "GET edit" do
    it "assigns the requested slot_machine as @slot_machine" do
      slot_machine = SlotMachine.create! valid_attributes
      get :edit, {:id => slot_machine.to_param}, valid_session
      assigns(:slot_machine).should eq(slot_machine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SlotMachine" do
        expect {
          post :create, {:slot_machine => valid_attributes}, valid_session
        }.to change(SlotMachine, :count).by(1)
      end

      it "assigns a newly created slot_machine as @slot_machine" do
        post :create, {:slot_machine => valid_attributes}, valid_session
        assigns(:slot_machine).should be_a(SlotMachine)
        assigns(:slot_machine).should be_persisted
      end

      it "redirects to the created slot_machine" do
        post :create, {:slot_machine => valid_attributes}, valid_session
        response.should redirect_to(SlotMachine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved slot_machine as @slot_machine" do
        # Trigger the behavior that occurs when invalid params are submitted
        SlotMachine.any_instance.stub(:save).and_return(false)
        post :create, {:slot_machine => { "name" => "invalid value" }}, valid_session
        assigns(:slot_machine).should be_a_new(SlotMachine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SlotMachine.any_instance.stub(:save).and_return(false)
        post :create, {:slot_machine => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested slot_machine" do
        slot_machine = SlotMachine.create! valid_attributes
        # Assuming there are no other slot_machines in the database, this
        # specifies that the SlotMachine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SlotMachine.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => slot_machine.to_param, :slot_machine => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested slot_machine as @slot_machine" do
        slot_machine = SlotMachine.create! valid_attributes
        put :update, {:id => slot_machine.to_param, :slot_machine => valid_attributes}, valid_session
        assigns(:slot_machine).should eq(slot_machine)
      end

      it "redirects to the slot_machine" do
        slot_machine = SlotMachine.create! valid_attributes
        put :update, {:id => slot_machine.to_param, :slot_machine => valid_attributes}, valid_session
        response.should redirect_to(slot_machine)
      end
    end

    describe "with invalid params" do
      it "assigns the slot_machine as @slot_machine" do
        slot_machine = SlotMachine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SlotMachine.any_instance.stub(:save).and_return(false)
        put :update, {:id => slot_machine.to_param, :slot_machine => { "name" => "invalid value" }}, valid_session
        assigns(:slot_machine).should eq(slot_machine)
      end

      it "re-renders the 'edit' template" do
        slot_machine = SlotMachine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SlotMachine.any_instance.stub(:save).and_return(false)
        put :update, {:id => slot_machine.to_param, :slot_machine => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested slot_machine" do
      slot_machine = SlotMachine.create! valid_attributes
      expect {
        delete :destroy, {:id => slot_machine.to_param}, valid_session
      }.to change(SlotMachine, :count).by(-1)
    end

    it "redirects to the slot_machines list" do
      slot_machine = SlotMachine.create! valid_attributes
      delete :destroy, {:id => slot_machine.to_param}, valid_session
      response.should redirect_to(slot_machines_url)
    end
  end

end
